### ISSUE TITLE
Add a claim function and /claims 

### ISSUE THREAD

**Issue by OmegaSybers** [Eisfunke/Secret-Hitler-Telegram#76] opened 2019-08-21 10:42 UTC
Within a round everybody who saw any card should be able to claim what he saw and make it public through a simple click on a button. And within a round you could see what claims were made with a simple command like /claims

**Comment by FRQDO** [comment] 2020-05-29 16:54
Dupe of #35

**Closed by FRQDO** 2020-05-29 16:54 UTC
Labels: enhancement
